kind: Deployment
apiVersion: apps/v1
metadata:
  name: user
spec:
  selector:
    matchLabels:
      app: user
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: user
        tier: backend
    spec:
      containers:
      - name: user-service
        image: user_server:dev
        ports:
        - containerPort: 80
