server:
  port: 8080

management:
  server:
    port: 9090

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://user-db.demo.svc.cluster.local:5432/userdb
    username: user_application
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

opentracing:
  jaeger:
    udp-sender:
      host: jaeger-agent.istio-system.svc.cluster.local
    enable-b3-propagation: true
    log-spans: true

logging:
  level:
    io.jaegertracing.internal.reporters.LoggingReporter: WARN

