java_binary(
    name = "spring_boot_packager",
    srcs = ["src/SpringBootPackager.java"],
    main_class = "src.SpringBootPackager",
    visibility = ["//visibility:public"],
    deps = [
        "@org_apache_commons_commons_compress//jar",
        "@org_springframework_boot_spring_boot_loader_tools//jar",
        "@org_springframework_spring_core//jar",
        "@org_springframework_spring_jcl//jar",
    ],
)
