kind: Deployment
apiVersion: apps/v1
metadata:
  name: user-db
spec:
  selector:
    matchLabels:
      app: user-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
      - name: postgres
        image: postgres:10.5-alpine
        env:
        - name: POSTGRES_USER
          value: user_application
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: userdb
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - name: pgsql
          containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresql-persistent-storage
      volumes:
      - name: postgresql-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim
