kind: Service
apiVersion: v1
metadata:
  name: user
spec:
  selector:
    app: user
    tier: backend
  ports:
  - name: http-web
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: http-mgmt
    protocol: TCP
    port: 9090
    targetPort: 9090
