kind: Service
apiVersion: v1
metadata:
  name: user
spec:
  selector:
    app: user
    tier: backend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: mgmt
    protocol: TCP
    port: 280
    targetPort: 9090
